### ISSUE TITLE
代码中numberFilter 觉得应该作为callback暴漏出来

### ISSUE THREAD

**Issue by dongruiyang** [tinglejs/tingle-number-field#2]
代码中numberFilter 觉得应该作为callback暴漏出来让各个应用自己去写自己需要map的数据格式以及过滤方法；放在代码中感觉跟业务绑定太强~

**Comment by jias** [comment]
需要自己的过滤方法时，请直接继承`text-field`，然后配置`filter`。

```
<TextField filter={your_own_filter}/>
```
